package cn.ptp.entity;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.name
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.parent_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private Integer parent_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param id the value for dept.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.name
     *
     * @return the value of dept.name
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.name
     *
     * @param name the value for dept.name
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.parent_id
     *
     * @return the value of dept.parent_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.parent_id
     *
     * @param parent_id the value for dept.parent_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }
}