package cn.ptp.entity;

import java.util.List;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.openid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.valid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.dept_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    private Integer dept_id;



    private Dept department;
    public Dept getDepartment(){
        return department;
    }
    public void setDepartment(Dept dept){
        this.department = dept;
    }

    private List<Role> roles;
    public List<Role> getRoles(){
        return roles;
    }
    public void setRoles(List<Role> roles){
        this.roles = roles;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.openid
     *
     * @return the value of user.openid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.openid
     *
     * @param openid the value for user.openid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.valid
     *
     * @return the value of user.valid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public Boolean getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.valid
     *
     * @param valid the value for user.valid
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setValid(Boolean valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.dept_id
     *
     * @return the value of user.dept_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public Integer getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.dept_id
     *
     * @param dept_id the value for user.dept_id
     *
     * @mbggenerated Thu Oct 27 15:00:23 CST 2016
     */
    public void setDept_id(Integer dept_id) {
        this.dept_id = dept_id;
    }
}