package com.i5018.hotel.sys.entity;

// Generated 2016-5-24 10:00:58 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar", catalog = "test")
public class Calendar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5347000893268547462L;
	private Integer id;
	private String title;
	private String start;
	private String end;
	private Short allday;
	private String color;

	public Calendar() {
	}

	public Calendar(String title, String start, String end, Short allday,
			String color) {
		this.title = title;
		this.start = start;
		this.end = end;
		this.allday = allday;
		this.color = color;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "start")
	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	@Column(name = "end")
	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	@Column(name = "allday")
	public Short getAllday() {
		return this.allday;
	}

	public void setAllday(Short allday) {
		this.allday = allday;
	}

	@Column(name = "color")
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
